# Generated by Django 3.2.5 on 2021-07-11 13:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 7, 11, 13, 6, 1, 489047, tzinfo=utc))),
                ('content', models.CharField(max_length=3000)),
                ('subject', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField()),
                ('max_score', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว')], max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=200)),
                ('student_id', models.IntegerField(max_length=8)),
                ('email_ref', models.EmailField(max_length=254)),
                ('group_ref', models.CharField(max_length=25)),
                ('score', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว')], max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('IS', 'อาจารย์ผู้สอน'), ('TA', 'นักศึกษาผู้ช่วยสอน')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 7, 11, 13, 6, 1, 489047, tzinfo=utc))),
                ('content', models.CharField(max_length=3000)),
                ('subject', models.CharField(max_length=100)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
            ],
            options={
                'verbose_name': 'Course Content',
                'verbose_name_plural': 'Course Contents',
            },
        ),
        migrations.CreateModel(
            name='Course_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 7, 11, 13, 6, 1, 489047, tzinfo=utc))),
                ('subject', models.CharField(max_length=100)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course_content')),
            ],
            options={
                'verbose_name': 'Course Comment',
                'verbose_name_plural': 'Course Comments',
            },
        ),
        migrations.CreateModel(
            name='Classwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(default=datetime.datetime(2021, 7, 11, 13, 6, 1, 491045, tzinfo=utc))),
                ('score', models.IntegerField(null=True)),
                ('graded', models.BooleanField(default=False)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.assignments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignments',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.instructor'),
        ),
    ]
